### ISSUE TITLE
Option to make property names as camel case

### ISSUE THREAD

**Issue by ankitmehtame** [postsharp/PostSharp.Community.ToString#5]
There should be an option to write property names as camel case instead of Pascal case, which is the standard convention.
For example:
```csharp
[ToString]
class TestClass
{
    public int FooBar { get; set; }
    public string Baz { get; set; }
}
```
If camel case option is selected, this should result in
```csharp
class TestClass
{
    public int FooBar { get; set; }
    public string Baz { get; set; }
    
    public override string ToString()
    {
        return $"TestClass; fooBar:{FooBar},baz:{Baz}";
    }
}
```

**Comment by Soothsilver** [comment]
This could be done in https://github.com/postsharp/PostSharp.Community.ToString/blob/master/Weaver/ToStringTask.cs at line 272 plus changes in `Configuration.cs` and the attribute itself.

Would you like to contribute? ^^

**Comment by ankitmehtame** [comment]
Thx. Will make the change.

**Comment by Soothsilver** [comment]
Uploaded to nuget.org as 1.3.0.

**Comment by ankitmehtame** [comment]
Thanks
