### ISSUE TITLE
Does this still work with PostSharp 6.10.8?

### ISSUE THREAD

**Issue by wouterroos** [postsharp/PostSharp.Community.ToString#7]
Hi,

I'm trying to get this to work in my solution but it doesn't show up in the PostSharp Explorer when I added it either as an assembly attribute or on a single class, nor does it seem to do anything at runtime.

I'm new to PostSharp so I could be doing something wrong, any help would be appreciated.

Thanks!

**Comment by addabis** [comment]
I'm sorry, we have missed this ticket. 

Community addins are not officially supported, but it seems to work for me with the latest version. Since these are not normal aspects, them not being visible in PostSharp Explorer is to be expected.

Are you still experiencing the problem?

**Comment by wouterroos** [comment]
@addabis I got it to work in the end so I closed the ticket.

Thanks!
